const names = [
  'Mount Everest',
  'K2',
  'Kangchenjunga',
  'Lhotse',
  'Makalu',
  'Cho Oyu',
  'Dhaulagiri',
  'Manaslu',
  'Nanga Parbat',
  'Annapurna',
  'Gasherbrum I',
  'Broad Peak',
  'Gasherbrum II',
  'Shishapangma',
  'Nanda Devi',
  'Rakaposhi',
  'Muztagh Tower',
  'Baruntse',
  'Pumori',
  'Gasherbrum III',
  'Gyachung Kang',
  'Annapurna II',
  'Gasherbrum IV',
  'Himalchuli',
  'Distaghil Sar',
  'Ngadi Chuli',
  'Nuptse',
  'Khunyang Chhish',
  'Masherbrum',
  'Nanda Devi',
  'Chomo Lonzo',
  'Batura Sar',
  'Kanjut Sar',
  'Rakaposhi',
  'Namcha Barwa',
  'Kamet',
  'Saltoro Kangri',
  'Jannu',
  'Tirich Mir',
  'Molamenqing',
  'Gurla Mandhata',
  'Saser Kangri',
  'Chogolisa',
  'Kongur Tagh',
  'Shispare',
  'Silberzacken',
  'Changtse',
  'Trivor',
  'Gangkhar Puensum',
  'Gongga Shan',
  'Annapurna III',
  'Kula Kangri',
  'Muztagh Ata',
  'Skyang Kangri',
  'Liankang Kangri',
  'Yukshin Gardan Sar',
  'Annapurna IV',
  'Saser Kangri II',
  'Mamostong Kangri',
  'Ismoil Somoni Peak',
  'Saser Kangri III',
  'Noshaq',
  'Pumari Chhish',
  'Passu Sar',
  'Malubiting',
  'Gangapurna',
  'Muchu Chhish',
  'Jengish Chokusu',
  'K12',
  'Sia Kangri',
  'Istor-o-Nal',
  'Ghent Kangri',
  'Haramosh Peak',
  'Kabru',
  'Ultar',
  'Rimo I',
  'Sherpi Kangri',
  'Labuche Kang',
  'Kirat Chuli',
  'Skil Brum',
  'Gimmigela Chuli',
  'Saraghrar',
  'Bojohagur Duanasir',
  'Chamlang',
  'Jomolhari',
  'Baltoro Kangri',
  'Siguang Ri',
  'The Crown',
  'Gyala Peri',
  'Porong Ri',
  'Baintha Brakk',
  'Yutmaru Sar',
  'K6',
  'Kangpenqing',
  'Mana Peak',
  'Muztagh Tower',
  'Diran',
  'Apsarasas Kangri',
  'Langtang Lirung',
  'Annapurna South',
  'Khartaphu',
  'Tongshanjiabu',
  'Langtang Ri',
  'Kangphu Kang',
  'Lupghar Sar',
  'Melungtse'
];

const colors = ['Pink', 'Red', 'Orange', 'Yellow', 'Green', 'Teal', 'Blue', 'Purple', 'Violet'];

const sampleColor = () => {
  const si = Math.floor(colors.length * Math.random());
  return colors.slice(si, si + 1)[0];
};

const sampleNames = () => {
  const si = Math.floor(names.length * Math.random());
  return names.slice(si, si + 1)[0];
};

export const getName = () => `${sampleColor()}-${sampleNames()}`.replace(' ', '-');
